name: Sleep-Mode Money Bot

on:
  schedule:
    - cron: '17 9 * * *'   # runs daily at 09:17 UTC
  workflow_dispatch:        # lets you run it manually

permissions:
  contents: write

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - env:
          POSTS_PER_RUN: "2"
        run: python scripts/generate_posts.py
      - run: |
          git config user.name "sleep-mode-bot"
          git config user.email "sleep-mode-bot@users.noreply.github.com"
          git add _posts/*.md || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "auto: daily posts"
            git push
          fi
